services:
  auth-service:
    image: auth-service-prod:1
    build: 
      context: ./services/auth-service/
      dockerfile : Dockerfile.prod
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      mongodb:
        condition: service_healthy
    restart : unless-stopped
    networks:
      - e-commerce-app
    secrets:
      - JWT_SECRET
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  order-service:
    image: order-service-prod:1
    build: 
      context: ./services/order-service/
      dockerfile : Dockerfile.prod
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      mongodb:
        condition: service_healthy
    restart : unless-stopped
    networks:
      - e-commerce-app
    secrets:
      - JWT_SECRET
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  product-service:
    image: product-service-prod:1
    build: 
      context: ./services/product-service/
      dockerfile : Dockerfile.prod
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      mongodb:
        condition: service_healthy
    restart : unless-stopped
    networks:
      - e-commerce-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    image: frontend-prod:1
    build: 
      context: ./frontend/
      dockerfile : Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - product-service
      - auth-service
      - order-service
    restart : unless-stopped
    networks:
      - e-commerce-app
  
  mongodb:
    image: mongo:8.2.5
    volumes:
      - db:/data/db
    restart : unless-stopped
    networks:
      - e-commerce-app
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

secrets:
  JWT_SECRET:
    file: ./secrets/jwt_secret.txt

volumes:
  db:

networks:
  e-commerce-app:
    driver: bridge
