FROM node:20-alpine

WORKDIR /opt/e-commerce/services/auth-service

RUN addgroup -S app && adduser -S app -G app

RUN npm install -g nodemon

COPY package*.json ./

RUN npm install

COPY . .

RUN chown -R app:app /opt/e-commerce

USER app

EXPOSE 3001

CMD ["npx", "nodemon", "--watch", ".", "src/app.js"]